name: flutter_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0


  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

